name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Install Fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Create default icon
      run: |
        mkdir -p icons
        convert -size 1024x1024 xc:white icons/icon.png

    - name: Initialize Go module
      run: go mod tidy

    - name: Build
      run: |
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          fyne package -os darwin -appID com.regattaclock.app -icon icons/icon.png
        else
          fyne package -os windows -appID com.regattaclock.app -icon icons/icon.png
        fi

    - name: Create DMG (macOS only)
      if: matrix.os == 'macos-latest'
      run: |
        hdiutil create -volname "Regatta Clock" -srcfolder "Regatta Clock.app" -ov -format UDZO "Regatta Clock.dmg"

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.os == 'macos-latest' && 'Regatta Clock.dmg' || 'Regatta Clock.exe' }}
        asset_name: ${{ matrix.os == 'macos-latest' && 'Regatta Clock.dmg' || 'Regatta Clock.exe' }}
        asset_content_type: ${{ matrix.os == 'macos-latest' && 'application/x-apple-diskimage' || 'application/x-msdownload' }} 